version: 2.1
executors:
  default:
    working_directory: /go/src/github.com/mattermost/mattermost-operator
    docker:
      - image: circleci/golang:1.12

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: kubebuilder
          command: |
            version=1.0.8
            curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_linux_amd64.tar.gz
            tar -zxvf kubebuilder_${version}_linux_amd64.tar.gz
            sudo mv kubebuilder_${version}_linux_amd64 /usr/local/kubebuilder
      - run: |
          export PATH=$PATH:/usr/local/kubebuilder/bin
          make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
